name: Print Env
description: Prints env secret and var
inputs:
  TEST_S:
    required: true
  TEST_V:
    required: true
runs:
  using: 'composite'
  steps:
    - name: print
      run: echo "secret - ${{ inputs.TEST_S }}, var - ${{ inputs.TEST_V }}"
      shell: bash