name: Filter changes in my_specific_folder 

on:
  push:
    branches:
      - "main"
    paths:
      - 'files/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: List all changed files
        run: |
          IFS=$'\n' files=($(git diff-tree --no-commit-id --name-only -r $(git rev-parse HEAD))) 
          for changed_file in "${files[@]}"; do
            echo "File - ${changed_file}"
            if [[ "${changed_file}" == files/* ]]; then
              filename=$(basename "${changed_file}")
              file_without_ext="${filename%.*}"
              echo "File - ${filename} - changed in my_specific_folder: ${file_without_ext}"
            fi
          done