name: Manual trigger example

on: [workflow_dispatch]

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    environment: 
      name: env1
      url: https://example.com/env1
    steps:
      - name: Do something
        run: echo "Hello from job 1"

  job2:
    name: Job 2
    runs-on: ubuntu-latest
    environment: 
      name: env2
      url: https://example.com/env2
    needs: job1
    steps:
      - name: Do something else
        run: echo "Hello from job 2"
    if: startsWith(github.ref, 'refs/tags/')
