name: Filter changes in my_specific_folder 

on:
  push:
    paths:
      - 'files/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'txt'
      - run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for changed_file in "${added_modified_files[@]}"; do
            if [[ "${changed_file}" == my_specific_folder/* ]]; then
              echo "File changed in my_specific_folder: ${changed_file}"
            fi
          done