name: Manual trigger example with env param

on:
  workflow_dispatch:
    inputs:
      fileName:
        description: file name to import, without extension
        required: true
      environment:
        type: environment
        description: 'Environment to deploy'
        required: true
        default: 'env1'

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment == '' && 'env1' || github.event.inputs.environment }}
    steps:
      - name: print
        run: echo "input - ${{ github.event.inputs.fileName }}"
        shell: bash

