name: Filter changes in my_specific_folder 

on:
  push:
    branches:
      - "main"
    paths:
      - 'files/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for changed_file in ${ALL_CHANGED_FILES}; do
            if [[ "${changed_file}" == files/* ]]; then
              filename=$(basename "${changed_file}")
              file_without_ext="${filename%.*}"
              echo "File - ${filename} - changed in my_specific_folder: ${file_without_ext}"
            fi
          done