name: Filter changes in my_specific_folder 

on:
  push:
    branches:
      - "main"
    paths:
      - 'files/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with full history
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: List all changed files
        run: |
          changed_files=$(git diff --name-only HEAD~1 HEAD)
          for changed_file in $changed_files
          do
            echo $changed_file
            if [[ $changed_file == files/* ]]; then
              filename=$(basename $changed_file)
              echo "File changed in my_specific_folder: ${filename}"
            fi
          done